# makefile
# Author: Julian Pineiro

main: SharedProcessMain.c
	gcc SharedProcessMain.c -o SharedProcess
	
# remove object files
clean: 							
	rm -f *.o core

# clean out object files and build both sources
build: clean main	
